### ISSUE TITLE
missing link to Raft paper by Tang Liu

### ISSUE THREAD

**Issue by kk3399** [pingcap/blog#23]
hey, i am interested in reading the paper by Tang Liu, could you either post the link as a response to the issue or update it in the post?

**Comment by queenypingcap** [comment]
@kk3399 Sorry for the delayed reply. Could you please be specific about which post and paper you are referring to?  Thanks a lot!

**Comment by kk3399** [comment]
the raft paper by Tang Liu in this post https://github.com/pingcap/blog/blob/0cdd07fca5cbf6d18dc6ef93997b138592161aed/_posts/2017-07-11-tidbinternal1.md

**Comment by queenypingcap** [comment]
@kk3399 Thanks for your interest! It's actually another blog written by Siddion Tang. The blog is currently written in Chinese. We will have it translated and keep you posted.

**Comment by queenypingcap** [comment]
Hi @kk3399 , the blog you mentioned is now translated into English. Please take a look:
https://pingcap.com/blog/optimizing-raft-in-tikv/

**Comment by queenypingcap** [comment]
The link is fixed here: https://github.com/pingcap/blog/blob/hugo-refactor/2017-07-11-tidbinternal1.md

Hence closing this issue.
