### ISSUE TITLE
how-we-build-tidb   Transaction问题

### ISSUE THREAD

**Issue by july2993** [pingcap/blog#6]
https://pingcap.github.io/blog/2016/10/17/how-we-build-tidb/
Transaction 部分最后两张图 Bob 跟 Joe Bal: Data timestamp 7 的值分别为6，6是不是搞错了，应该是前面的3，9吧？

**Comment by siddontang** [comment]
Thanks @july2993 

This is typo, we will fix it later.

**Comment by queenypingcap** [comment]
Thanks and sorry for the delay, @july2993, this issue is now fixed.
